### ISSUE TITLE
Incorrect Meetup Information while using 'nextmeetup' command

### ISSUE THREAD

**Issue by sahilsharma811** [realslimshanky/PyDelhi-Bot#2]
Bot is not showing the correct schedule when the bot is invoked using the nextmeetup command.The reason for the same is the new architecture of the www.meetup.com website.

**Comment by realslimshanky** [comment]
Hi @sahilsharma811, please give a detailed information you are getting which can be analyzed in order to make the bot better.

**Comment by realslimshanky** [comment]
Closing this issue as I cannot find the problem.
